language: python

dist: bionic

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install bandit flake8
  - python setup.py install

script:
  - flake8 floodfill
  - bandit -r floodfill
  - python -m unittest --verbose tests
