language: python

dist: bionic

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install bandit flake8 coverage coveralls
  - python setup.py install

script:
  - flake8 floodfill
  - bandit -r floodfill
  - coverage run --source=floodfill -m tests --verbose
  - coverage report -m

after_success:
  - pip install sphinx sphinx-rtd-theme
  - make -C docs clean html
  - touch docs/build/html/.nojekyll # create this file to prevent Github's Jekyll processing
  - coveralls

deploy:
  provider: pages
  verbose: true
  keep_history: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build/html
  on:
    branch: master
    python: "3.8"
